### PR TITLE
add capture of other lead-ads metadata; move verify-token to an environment var

### PR DESCRIPTION
**Pull request by cgrayson**

### CODE REVIEW

**Comment by cgrayson** [comment]
Forgot to point out: this integration is all new, please eyeball the whole thing. :eyes:

**Comment by cgrayson** [comment]
Fixed the things you mentioned; anything else, or still looking?

**Comment by alexkwolfe** [comment]
Still looking.

**Comment by alexkwolfe** [comment]
I don't see anything else.

**Pull request merged**
